# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Mirrly"
client_id = "9d72bb0915715baf6d8d8b6b9bb15d29"
application_url = "https://mirrly.test"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_script_tags,read_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mirrly.test/auth/callback",
  "https://mirrly.test/auth/shopify/callback",
  "https://mirrly.test/api/auth/callback",
  "https://mirrly.test"
]

[webhooks]
api_version = "2026-07"

[pos]
embedded = false

[build]
